@baseUrl = http://localhost:3003/api

### 

GET {{baseUrl}}/users

### 

GET {{baseUrl}}/users/1

### 

GET {{baseUrl}}/users/999

###

POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "test@example.com",
  "password_hash": "hashed_password_123",
  "role": "user"
}